#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 16 17:24:59 2021

@author: elliott
"""

import pydatadarn
import json

import numpy as np

#acces spherically fitted data generated by get_convection_data.py
fname = "20131002_083000.json"
with open(fname) as json_file:
	data = json.load(json_file)
	
plasma_mcolats = np.array(data["plasma_mcolats"])
plasma_mlons = np.array(data["plasma_mlons"])
plasma_az = np.array(data["plasma_az"])
plasma_vels = np.array(data["plasma_vels"])
time_i = data["time"]
uao_neutral_az = np.array(data["uao_neutral_kvec"])
uao_neutral_vel = np.array([data["uao_neutral_vel"]])
boundary_mlats = np.array(data["hmb_mlats"])
boundary_mlons = np.array(data["hmb_mlons"])
	
dr, dtheta = pydatadarn.vector_plot(plasma_mcolats, plasma_mlons, plasma_az, plasma_vels, time=time_i, 
								station_names=["bks"], FPI_names=["uao"], 
								FPI_kvecs=uao_neutral_az, FPI_vels=uao_neutral_vel, 
								boundary_mlats=boundary_mlats, boundary_mlons=boundary_mlons, 
								mlt=False, cart=True,
								colat_min=60, colat_max=0, lon_min=-125, lon_max=-65)